// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtLuqCuOy9ec-iiK03Eqph_muC9x62wRg',
    appId: '1:303543423712:web:3a42d73f4ba1efbb187685',
    messagingSenderId: '303543423712',
    projectId: 'riverpodfirestore',
    authDomain: 'riverpodfirestore.firebaseapp.com',
    storageBucket: 'riverpodfirestore.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHJzdzPPZfa_2O-27Kp3RTVjD2DMOmUkE',
    appId: '1:303543423712:android:958f6d90a7a8bffc187685',
    messagingSenderId: '303543423712',
    projectId: 'riverpodfirestore',
    storageBucket: 'riverpodfirestore.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoOEfAdtlw7stUbfNqwUbrvTuvYNqa8V0',
    appId: '1:303543423712:ios:0dacf0ca52e1b589187685',
    messagingSenderId: '303543423712',
    projectId: 'riverpodfirestore',
    storageBucket: 'riverpodfirestore.appspot.com',
    iosClientId: '303543423712-d5kou5esjmlqea08j9ij4t2speqi3oga.apps.googleusercontent.com',
    iosBundleId: 'shop.mtcoding.riverpodFirestoreStream',
  );
}
